#ifndef __CONFIG_H__
#define __CONFIG_H__

#define CONFIG_BOARD_HSE_CLK 25000000U
#define CONFIG_BOARD_HSE_BYP 0
#define CONFIG_BOARD_SYS_CLK 100000000U

#define CONFIG_ARCH_AARCH32 1
#define CONFIG_ARCH_SUB_ARMV7E_M 1
#define CONFIG_ARCH_CPU_FAMILY_STM32F7 1
#define CONFIG_ARCH_CPU_STM32F769 1
#define CONFIG_CM7_ART_ACCELERATOR_ENABLE 1
#define CONFIG_CM7_PREFETCH_ENABLE 1

#endif/*__CONFIG_H__*/
